package mk.ukim.finki.bnks_project.model;

public class SignedRequestLog {
    /* TODO: entity to save history of signed user requests for each keyId. (So that no replay attack),
        maybe has fields: autogeneratedId, keyId, date (The date te key associated with that keyId was used for signing and verification
    */
}
