###

GET http://localhost:8080/api/simplekey/dummy

###

GET http://localhost:8080/api/welcome

###

POST http://localhost:8080/api/welcome/post

###

POST http://localhost:8080/api/users/register
Content-Type: application/json

{"username":"johnny","password":"cats1234"}

###

POST http://localhost:8080/api/users/login
Content-Type: application/json

{"username":"test1","password":"password1"}

###

POST http://localhost:8080/api/users/login
Content-Type: application/json

{"username":"anne","password":"doge"}

###

POST http://localhost:8080/api/signedendpoint/posttest
Authenticate: flwfhlhwefhweiohfiow
X-Timestamp: 29841144
X-Algorithm: METHOD+PATH+TIMESTAMP+BODY

{"hello":"blah"}
###

###
GET http://localhost:8080/api/users/fetchall
Authentication: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MSIsImV4cCI6MTU5NDc0ODMwNywiaWF0IjoxNTk0NzMwMzA3fQ.O_jhJH8CASbSIbwy4849_02SCptU661bZdk3Y4pSFrBkrIloJwXs4ObgzXoV320lvnKEge2zYLEN9RR4whLW-g
Content-Type: application/json
###